### ISSUE TITLE
Rewrite the Glossary Definitions

### ISSUE THREAD

**Issue by hydrogenbond007** [wormhole-foundation/docs.wormhole.com#101]
Rewrite the outdated definitions of a few terms in the [Glossary section of docs](https://docs.wormhole.com/wormhole/reference/glossary)

> xChain
Term that refers to the full range of cross-blockchain interoperability.
xAssets
Chain-and-path agnostic token that exists on a layer outside the blockchain ecosystem, which can be used to conduct transactions on any blockchain.
xDapp
Decentralized application that enables users to create and/or use xData.
xData
Data that exists in a layer outside of Layer 1 blockchains, which is accessible by all chains.

**Comment by barnjamin** [comment]
lets leave these for now in case there is outdated material elsehwere
