### ISSUE TITLE
Standardize Terminology

### ISSUE THREAD

**Issue by barnjamin** [wormhole-foundation/docs.wormhole.com#6]
There are a number of terms we interchange, like "Origin" and "Source" to mean the chain or contract from which some relevant message was issued. 

We should be as consistent as possible in the docs and make sure the glossary mentions "Also called ..." to explain content from sources outside the docs

**Comment by akshatcoder-hash** [comment]
hey @barnjamin! I would love to work on this issue! Could you please assign this to me?

**Comment by barnjamin** [comment]
I can but I'll say I'm not sure exactly how much needs to be done in the docs. 

We should try to document things "as they are" in code for now but be sure to make it clear that sometimes certain terms are used interchangeably. 

This may be as simple as adding entries to the glossary and cross linking them
